### ISSUE TITLE
Exciting to see this resurrected! Is it currently functional? Do you need assistance?

### ISSUE THREAD

**Issue by kegbuna** [heymdall-legal/thrift-api-ui#1]
Hello,

I am a developer that works with Thrift services and was wondering if this was already functional and whether you needed assistance for it. If so, feel free to create some issues and maybe I can get some time dedicated to helping out. It's really great to see something like this get resurrected as the Thrift community is in dire need of tooling like this.

I would label this just a question but I can't seem to modify that field.

Thanks!

**Comment by heymdall-legal** [comment]
Hi there. Well I'm glad that someone actually need this tool outside of my company. 
It's currently fully functional and used widely across my company for a last couple of years.
As for issues - I don't actively maintain this project, right now it seems that latest release got all features that I and my teammates need. I just restore this repo, because my previous github account was blocked.
But if you have some features in mind or encounter some bugs - feel free to open new issues and I will try to make time for it.
